sudo: false

language: node_js

node_js:
- "0.12"
- "0.10"

os:
- linux
- osx

matrix:
  allow_failures:
    - os: osx

install:
- export CXX="g++-4.8" CC="gcc-4.8"

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - libboost-all-dev
    - libcurl4-openssl-dev
    - uuid-dev
    - g++-4.8

script: npm run-script ci
