init:
  - git config --global core.autocrlf input

shallow_clone: true

environment:
  matrix:
    - nodejs_version: "6.9.1"
    - nodejs_version: "7.0.0"

matrix:
  fast_finish: true

install:
  - ps: Install-Product node $env:nodejs_version x64
  - pip install --egg scons

test_script:
  - node --version
  - npm --version
  - pip --version
  - npm install -g grunt-cli
  - npm run-script test

build: off
